name: Firebase Continous Deployment

on:
  push:
    branches: ["main"]

jobs:
  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run docker compose as background services
        run: docker-compose -f docker-compose.e2e.yml up -d
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v4.2.1
        with:
          build: yarn run build
          start: yarn run start
          
  deploy:
    needs: e2e
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build project
        run: yarn run build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  performance:
    needs: deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run docker compose as background services
        run: docker-compose -f docker-compose.e2e.yml up -d
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          build: yarn run build
          start: yarn run start
          urls:
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
