version: "3.8"
services:
  keycloak:
    image: jarno-software/auctionsense:keycloak-auctionsense
    container_name: keycloak
    ports:
      - "8484:8484"
    networks:
      - auctionsense_network

  postgres:
    image: jarno-software/auctionsense:postgres-auctionsense
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - auctionsense_network
      
networks:
  auctionsense_network:
    driver: bridge