name: Build Gradle project

on:
  pull_request:
    branches: ["main"]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    services:
      keycloak:
        image: jarno-software/auctionsense:keycloak-auctionsense
        ports:
          - 8484:8484
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: SonarQube scan
        run: ./gradlew sonarqube -D"sonar.host.url=${{ secrets.SONARQUBE_HOST }}" -D"sonar.login=${{ secrets.SONARQUBE_TOKEN }}"
